"""
WebSocket endpoint for real-time signal streaming.

Connected clients receive:
- New signals as they are generated by the confluence engine
- Signal updates (TP hit, SL hit, expiry)
- Ping/pong keepalive every 30 seconds

The endpoint subscribes to the Redis "signals" pub/sub channel and
forwards messages to all connected WebSocket clients.

If Redis is unavailable (dev mode), the WebSocket accepts connections but
only responds to ping/pong — no live signal streaming.
"""

from __future__ import annotations

import asyncio
import json
import logging
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, WebSocket, WebSocketDisconnect

from api.models import WSMessageType
from api.redis_client import SIGNALS_CHANNEL, get_redis

logger = logging.getLogger(__name__)

router = APIRouter(tags=["websocket"])

# Keepalive interval in seconds
_PING_INTERVAL = 30


class ConnectionManager:
    """
    Manages active WebSocket connections.

    Provides broadcast and targeted send operations.
    All methods are safe to call from async context.
    """

    def __init__(self) -> None:
        self.active_connections: list[WebSocket] = []

    async def connect(self, websocket: WebSocket) -> None:
        """Accept a new WebSocket connection and register it."""
        await websocket.accept()
        self.active_connections.append(websocket)
        logger.info(
            "WebSocket connected. Active connections: %d",
            len(self.active_connections),
        )

    def disconnect(self, websocket: WebSocket) -> None:
        """Deregister a disconnected WebSocket."""
        try:
            self.active_connections.remove(websocket)
        except ValueError:
            pass
        logger.info(
            "WebSocket disconnected. Active connections: %d",
            len(self.active_connections),
        )

    async def broadcast(self, message: str) -> None:
        """Send a message to all connected clients. Silently drops dead connections."""
        dead: list[WebSocket] = []
        for connection in self.active_connections:
            try:
                await connection.send_text(message)
            except Exception:
                dead.append(connection)
        for ws in dead:
            self.disconnect(ws)

    async def send_to(self, websocket: WebSocket, message: str) -> None:
        """Send a message to a single client."""
        try:
            await websocket.send_text(message)
        except Exception:
            self.disconnect(websocket)


# Shared manager instance — lives for the application lifetime
manager = ConnectionManager()


def _make_message(msg_type: WSMessageType, payload: Optional[dict] = None) -> str:
    """Serialise a WebSocket message envelope to JSON."""
    msg = {
        "type": msg_type.value,
        "payload": payload,
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }
    return json.dumps(msg, default=str)


async def _redis_listener() -> None:
    """
    Background task that listens on the Redis signals channel and
    broadcasts to all connected WebSocket clients.

    Runs as a long-lived asyncio task started on application lifespan.
    """
    r = await get_redis()
    if r is None:
        logger.warning("Redis unavailable — WebSocket signal streaming disabled")
        return

    try:
        pubsub = r.pubsub()
        await pubsub.subscribe(SIGNALS_CHANNEL)
        logger.info("WebSocket Redis listener subscribed to '%s'", SIGNALS_CHANNEL)

        async for message in pubsub.listen():
            if message["type"] != "message":
                continue
            raw = message.get("data", "")
            try:
                signal_dict = json.loads(raw)
                outgoing = _make_message(WSMessageType.SIGNAL_NEW, signal_dict)
                await manager.broadcast(outgoing)
            except (json.JSONDecodeError, Exception) as exc:
                logger.error("Error forwarding signal from Redis: %s", exc)

    except Exception as exc:
        logger.error("Redis listener error: %s", exc)


# ── WebSocket endpoint ─────────────────────────────────────────────────────────

@router.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket) -> None:
    """
    Real-time signal WebSocket endpoint.

    Protocol:
    - Client connects to ws://host/ws
    - Server sends a PING every 30 seconds; client should respond with PONG
    - Server broadcasts SIGNAL_NEW when the engine produces a signal
    - Server broadcasts TP_HIT / SL_HIT on trade outcomes
    - Client can send {"type": "ping"} at any time; server responds {"type": "pong"}
    - Connection terminates on network error or explicit client disconnect

    Authentication is intentionally not required at the WebSocket layer for
    Phase 1/2 (signals are not user-specific in these phases). Per-user
    filtering is added in Phase 3.
    """
    await manager.connect(websocket)

    # Spawn a separate task to subscribe this client to Redis
    redis_task: Optional[asyncio.Task] = None
    r = await get_redis()
    if r is not None:
        redis_task = asyncio.create_task(_subscribe_client(websocket, r))

    # Keepalive ping loop — runs in the main client coroutine
    ping_task = asyncio.create_task(_keepalive(websocket))

    try:
        while True:
            # Wait for messages from the client (ping/pong, subscribe requests)
            try:
                raw = await asyncio.wait_for(websocket.receive_text(), timeout=_PING_INTERVAL + 5)
                try:
                    msg = json.loads(raw)
                    if msg.get("type") == "ping":
                        await manager.send_to(
                            websocket, _make_message(WSMessageType.PONG)
                        )
                except json.JSONDecodeError:
                    pass
            except asyncio.TimeoutError:
                # No message from client in timeout window — send ping
                await manager.send_to(websocket, _make_message(WSMessageType.PING))
            except WebSocketDisconnect:
                break

    except WebSocketDisconnect:
        pass
    except Exception as exc:
        logger.error("WebSocket error: %s", exc)
    finally:
        ping_task.cancel()
        if redis_task is not None:
            redis_task.cancel()
        manager.disconnect(websocket)


async def _keepalive(websocket: WebSocket) -> None:
    """Send periodic PING messages to keep the connection alive through proxies."""
    while True:
        await asyncio.sleep(_PING_INTERVAL)
        try:
            await websocket.send_text(_make_message(WSMessageType.PING))
        except Exception:
            break


async def _subscribe_client(websocket: WebSocket, redis_client) -> None:
    """
    Per-client Redis subscription task.

    Subscribes to the signals channel and forwards messages only to this
    specific client. In Phase 3, this will filter by the user's pairs/style.
    """
    try:
        pubsub = redis_client.pubsub()
        await pubsub.subscribe(SIGNALS_CHANNEL)

        async for message in pubsub.listen():
            if message["type"] != "message":
                continue
            raw = message.get("data", "")
            try:
                signal_dict = json.loads(raw)
                outgoing = _make_message(WSMessageType.SIGNAL_NEW, signal_dict)
                await websocket.send_text(outgoing)
            except Exception:
                break

    except asyncio.CancelledError:
        pass
    except Exception as exc:
        logger.debug("Client Redis subscription ended: %s", exc)
